# Generated by Django 2.2.18 on 2021-02-14 14:31

from django.db import migrations


def load_initial_content(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Audio = apps.get_model('pages', 'Audio')
    Video = apps.get_model('pages', 'Video')
    Text = apps.get_model('pages', 'Text')
    Page = apps.get_model('pages', 'Page')

    audio_1 = Audio.objects.create(title='Red Hot Chili Peppers - Snow', bit_rate=256)
    audio_2 = Audio.objects.create(title='Kings Of Leon - Cold Desert', bit_rate=512)
    audio_3 = Audio.objects.create(title='Metallica - The Outlaw Torn', bit_rate=293)
    audio_4 = Audio.objects.create(title="Oasis - Don't Look Back in Anger", bit_rate=344)
    audio_5 = Audio.objects.create(title='Green Day - Boulevard Of Broken Dreams', bit_rate=128)

    video_1 = Video.objects.create(title='The Shawshank Redemption', video_file_link='https://videos.com/1', subtitles_file_link='https://subtitles.com/1')
    video_2 = Video.objects.create(title='The Godfather', video_file_link='https://videos.com/2', subtitles_file_link='https://subtitles.com/2')
    video_3 = Video.objects.create(title='The Godfather: Part II', video_file_link='https://videos.com/2', subtitles_file_link='https://subtitles.com/3')
    video_4 = Video.objects.create(title='The Dark Knight', video_file_link='https://videos.com/2', subtitles_file_link='https://subtitles.com/4')
    video_5 = Video.objects.create(title='12 Angry Men', video_file_link='https://videos.com/2', subtitles_file_link='https://subtitles.com/5')

    text_1 = Text.objects.create(title='In Search of Lost Time', body='Some In Search of Lost Time text')
    text_2 = Text.objects.create(title='Ulysses', body='Some Ulysses text')
    text_3 = Text.objects.create(title='Don Quixote', body='Some Don Quixote text')
    text_4 = Text.objects.create(title='One Hundred Years of Solitude', body='Some One Hundred Years of Solitude text')
    text_5 = Text.objects.create(title='The Great Gatsby', body='Some The Great Gatsby text')

    page_1 = Page.objects.create(title='First page')
    page_1.audios.add(audio_1, audio_2, audio_3)
    page_1.videos.add(video_5, video_4)
    page_1.texts.add(text_2, text_4)

    page_2 = Page.objects.create(title='Second page')
    page_2.audios.add(audio_1, audio_3)
    page_2.texts.add(text_3)

    page_3 = Page.objects.create(title='Third page')
    page_3.videos.add(video_1)

    page_4 = Page.objects.create(title='Fourth page')
    page_4.audios.add(audio_4)
    page_4.videos.add(video_4)
    page_4.texts.add(text_5)

    page_5 = Page.objects.create(title='Fifth page')
    page_5.audios.add(audio_5)
    page_5.videos.add(video_2, video_3)
    page_5.texts.add(text_1)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_models'),
    ]

    operations = [
        migrations.RunPython(load_initial_content),
    ]
